### PR TITLE
Propagate options

### PR DESCRIPTION
**Pull request by joao-conde**
| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | -- |
| Decisions | `ensure*` and related methods should receive options and propagate them. `build` receives the owner and `init` expects it |

### CODE REVIEW

**Review by gcandal — APPROVED** [review]

**Comment by joamag** [comment]
Closing this as using options in singletons is an anti-pattern

**Comment by joamag** [comment]
The correct fix for the random name in group id for singleton https://github.com/ripe-tech/ripe-bus-api-js/commit/c2fcf779aba91dd785b079ef720dab60837b0799

**Comment by gcandal** [comment]
@joao-conde you can configure it with an env var

**Comment by joao-conde** [comment]
> 
> 
> The correct fix for the random name in group id for singleton [c2fcf77](https://github.com/ripe-tech/ripe-bus-api-js/commit/c2fcf779aba91dd785b079ef720dab60837b0799)

Was going to do it [here](https://github.com/ripe-tech/ripe-bus-api-js/tree/jc/uuid-consumer-id) but was still dealing with the error which I see you dealt with

**Pull request closed without merging**
